services:
  php:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: projeto-academia
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - rede-academia

  mysql:
    image: mysql:8.0
    container_name: academia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha_root_123
      MYSQL_DATABASE: projeto_academia
      MYSQL_USER: usuario_app
      MYSQL_PASSWORD: senha_app_123
    volumes:
      - dados_mysql:/var/lib/mysql
      - ./Docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - rede-academia

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: academia_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: senha_root_123
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - rede-academia

volumes:
  dados_mysql: {}

networks:
  rede-academia:
    driver: bridge