/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./**/*.{html,php,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "surface-container": "#1f2020",
        "surface-tint": "#abd600",
        "on-primary-fixed": "#161e00",
        "inverse-on-surface": "#303030",
        "surface": "#131313",
        "on-background": "#e4e2e1",
        "error": "#ffb4ab",
        "inverse-primary": "#506600",
        "on-primary": "#283500",
        "on-primary-container": "#556d00",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#c6c6c7",
        "surface-container-highest": "#353535",
        "on-secondary": "#2f3132",
        "secondary": "#c6c6c7",
        "on-surface-variant": "#c4c9ac",
        "tertiary-fixed": "#e5e2e1",
        "tertiary-container": "#e5e2e1",
        "outline": "#8e9379",
        "on-tertiary-fixed-variant": "#474746",
        "primary-fixed": "#c3f400",
        "on-tertiary-fixed": "#1c1b1b",
        "on-secondary-fixed": "#1a1c1d",
        "surface-dim": "#131313",
        "secondary-fixed": "#e2e2e3",
        "tertiary-fixed-dim": "#c8c6c5",
        "secondary-container": "#454748",
        "surface-variant": "#353535",
        "surface-container-lowest": "#0e0e0e",
        "primary-container": "#c3f400",
        "primary-fixed-dim": "#abd600",
        "on-tertiary-container": "#656464",
        "on-secondary-fixed-variant": "#454748",
        "tertiary": "#ffffff",
        "primary": "#ffffff",
        "background": "#131313",
        "on-secondary-container": "#b4b5b6",
        "on-primary-fixed-variant": "#3c4d00",
        "inverse-surface": "#e4e2e1",
        "on-surface": "#e4e2e1",
        "outline-variant": "#444933",
        "surface-bright": "#393939",
        "surface-container-high": "#2a2a2a",
        "on-tertiary": "#313030",
        "surface-container-low": "#1b1c1c",
        "on-error": "#690005",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter": "24px",
        "container-padding-desktop": "32px",
        "container-padding-mobile": "16px",
        "section-gap": "64px",
        "base": "8px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}